export const SESSION_EVENT_TYPES = {
  ROOM_CREATED: "ROOM_CREATED",
  PARTICIPANT_JOINED: "PARTICIPANT_JOINED",
  QUIZ_STARTED: "QUIZ_STARTED",
  QUESTION_STARTED: "QUESTION_STARTED",
  QUESTION_CLOSED: "QUESTION_CLOSED",
  ANSWER_SHOWN: "ANSWER_SHOWN",
  ANSWER_SUBMITTED: "ANSWER_SUBMITTED",
  QUIZ_FINISHED: "QUIZ_FINISHED",
  QUIZ_CANCELLED: "QUIZ_CANCELLED",
} as const;

export type SessionEventType =
  (typeof SESSION_EVENT_TYPES)[keyof typeof SESSION_EVENT_TYPES];
